date_format_search = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"
date_format = "%Y-%m-%dT%H:%M:%SZ"
date_format_message = "Date format must be YYYY-MM-DDTHH:MM:SSZ"
deletion_message = "Deletion was successful!"

abbreviation_ct = "KÜ"
abbreviation_co = "EK"
abbreviation_rq = "RQ"
abbreviation_se = "SE"
abbreviation_fo = "FO"
abbreviation_rm = "ZL"
abbreviation_an = "AN"
abbreviation_ec = "ÜB"
abbreviation_ex = "BE"
abbreviation_ra = "AB"
abbreviation_cc = "ZF"
abbreviation_as = "LZ"

name_perception_dimension = "perception_dimension"
name_input_dimension = "input_dimension"
name_processing_dimension = "processing_dimension"
name_understanding_dimension = "understanding_dimension"
name_perception_value = "perception_value"
name_input_value = "input_value"
name_processing_value = "processing_value"
name_understanding_value = "understanding_value"
